# Refer https://github.com/zyrouge/pong#configuration for documentation

urls:
  - path: "https://eseqtech.com"
    type: "get"
  - path: "http://forum.eseqtech.com"
    type: "get"
  - path: "http://hexp.net"
    type: "get"
  - path: "http://ws.hexp.net"
    type: "get"
  - path: "http://eseqtech.com/infoline"
    type: "get"
